# Generated by Django 2.2.2 on 2019-09-23 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chessgame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moves', models.TextField()),
                ('date_and_time', models.DateTimeField()),
            ],
        ),
        #migrations.DeleteModel(
        #    name='User2',
        #),
        migrations.AddField(
            model_name='profile',
            name='rating',
            field=models.PositiveSmallIntegerField(default=1500),
        ),
        migrations.AddField(
            model_name='chessgame',
            name='black',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='white', to='website.Profile', unique=True),
        ),
        migrations.AddField(
            model_name='chessgame',
            name='white',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='black', to='website.Profile', unique=True),
        ),
    ]
