# Generated by Django 2.2.2 on 2019-09-23 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20190923_1150'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User2',
        ),
    ]
