# Generated by Django 2.2.2 on 2020-02-10 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_user2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='rating',
        ),
        migrations.DeleteModel(
            name='Chessgame',
        ),
    ]
