# Generated by Django 2.2.2 on 2020-02-24 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_auto_20200210_2004'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.IntegerField()),
                ('white_player', models.TextField()),
                ('black_player', models.TextField()),
                ('white_rating', models.IntegerField()),
                ('black_rating', models.IntegerField()),
                ('moves', models.TextField()),
                ('winner', models.TextField()),
                ('end_result', models.TextField()),
                ('start_time', models.IntegerField()),
                ('increment', models.IntegerField()),
                ('date_played', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
